// <auto-generated />
namespace Autenticacao.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11052017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11052017));
        
        string IMigrationMetadata.Id
        {
            get { return "201705111809069_11052017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
